# Generated by Django 4.2.3 on 2023-08-03 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='required_amount_to_use_coupon',
            field=models.PositiveIntegerField(default=100),
            preserve_default=False,
        ),
    ]
